"""Rebuild the NITRO movement figures. Run from anywhere: python3 tools/pose-rig/final.py
Writes poses.js, poses/*.svg and poses/index.html (a gallery) at the repo root."""
import json, os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
import build, rig
from reg import MOVES
build.load(['m_a1', 'm_a2', 'm_b1', 'm_b2', 'm_c1', 'm_c2', 'm_w', 'm_gym'])
os.makedirs(os.path.join(ROOT, 'poses'), exist_ok=True)
rig.WARN.clear()
js = {}
for n, fr in MOVES.items():
    open(os.path.join(ROOT, 'poses', rig.slug(n) + '.svg'), 'w').write(rig.card(fr, n, embed=True))
    lite = rig.card(fr, n, embed=False).replace(' role="img"', ' aria-hidden="true" focusable="false"')
    js[n] = re.sub(r'<rect y="-?[0-9]+" width[^>]*/>', '', lite, count=1)   # the page supplies the paper
open(os.path.join(ROOT, 'poses.js'), 'w').write(
    '/* NITRO movement figures: one start/end card per move, drawn from a single skeleton.\n'
    '   Generated by tools/pose-rig/final.py. Keyed by the exact move name used in index.html. */\n'
    'window.NITRO_POSES = ' + json.dumps(js, ensure_ascii=False, separators=(',', ':')) + ';\n')
cells = ''.join(f'<figure><figcaption>{n}</figcaption><div class="fig">{svg}</div></figure>' for n, svg in js.items())
open(os.path.join(ROOT, 'poses', 'index.html'), 'w').write(
    '<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NITRO figures</title>'
    '<style>:root{--paper:#fff;--ink:#000;--g:#777}@media(prefers-color-scheme:dark){:root{--paper:#000;--ink:#fff;--g:#999}}'
    'body{margin:16px;background:var(--paper);color:var(--ink);font:600 14px system-ui}main{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:14px}'
    'figure{margin:0;border:2px solid var(--ink)}figcaption{padding:6px 10px;border-bottom:2px solid var(--ink)}'
    '.fig svg{display:block;width:100%;height:auto}.fig .i{stroke:var(--ink);fill:none}.fig .g{stroke:var(--g);fill:none}.fig .p{stroke:var(--paper);fill:none}'
    '.fig .f{fill:var(--ink)}.fig .pf,.fig .i.pf{fill:var(--paper)}.fig .f.p{fill:var(--ink);stroke:var(--paper)}.fig g{stroke-linecap:round;stroke-linejoin:round}'
    '.fig text{font:700 15px ui-monospace,monospace;fill:var(--ink);stroke:none}</style>'
    f'<h1 style="font-size:18px">NITRO movement figures ({len(js)})</h1><main>{cells}</main>')
print(len(js), 'figures written;', len(rig.WARN), 'moves nudged by the reach check (all under a few px)')
idx = os.path.join(ROOT, 'index.html')
if os.path.exists(idx):
    names = set(re.findall(r"\{n:(?:'((?:[^'\\]|\\.)*)'|\"((?:[^\"\\]|\\.)*)\"),\s*eq:", open(idx).read()))
    names = {(a or b).replace("\\'", "'") for a, b in names}
    print('moves in index.html without a figure:', sorted(names - set(js)) or 'none')
